FROM python:3.12-slim

WORKDIR /app

COPY streamlit/app.py .
COPY requirements.streamlit.txt .

RUN pip install --no-cache-dir -r requirements.streamlit.txt

EXPOSE 8501

CMD ["streamlit", "run", "app.py"]