FROM python:3.12-slim

WORKDIR /app

COPY requirements.txt .
COPY pipelines/ pipelines/
COPY steps/ steps/
COPY src/ src/
COPY run_deployment.py .
COPY config.yaml .

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["python", "run_deployment.py"]